---
driver:
  name: vagrant
  memory: 1024
  cpus: 1

provisioner:
  name: nodes
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  product_name: chef
  product_version: 12
  log_level: info

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: node-1
    driver:
      network:
      - ['private_network', {ip: '192.168.12.12'}]
    run_list:
      - recipe[docker-cluster::leader]
      - recipe[hurry-up-and-test::set_non_nat_vbox_ip]
      - recipe[hurry-up-and-test::export_node]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node-2
    driver:
      network:
      - ['private_network', {ip: '192.168.12.13'}]
    run_list:
      - recipe[docker-cluster::follower]
      - recipe[hurry-up-and-test::export_node]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node-3
    driver:
      network:
      - ['private_network', {ip: '192.168.12.14'}]
    run_list:
      - recipe[docker-cluster::follower]
      - recipe[hurry-up-and-test::export_node]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
