---
driver:
  name: vagrant
  memory: 1024
  cpus: 1

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  product_name: chef 
  product_version: 12

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: node-1 
    driver:
      network:
      - ['private_network', {ip: '192.168.12.12'}]
    run_list:
      - recipe[docker-cluster::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node-2 
    driver:
      network:
      - ['private_network', {ip: '192.168.12.13'}]
    run_list:
      - recipe[docker-cluster::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node-3
    driver:
      network:
      - ['private_network', {ip: '192.168.12.14'}]
    run_list:
      - recipe[docker-cluster::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
